require:
  - rubocop-disable_syntax
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "vendor/**/*"

Style/DisableSyntax:
  DisableSyntax:
    - unless
    - ternary
    - endless_methods
    - numbered_parameters
    - shorthand_hash_syntax
    - percent_literals

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
